### ISSUE TITLE
Modification changement main

### ISSUE THREAD

**Issue by Anth0ny29** [StefForBSI/JeudeLOieGrA#14]
La fonction condEgal prend 3 paramètres et non 2.

https://github.com/StefForBSI/JeudeLOieGrA/blob/9603d14fd09dd2746ffd86e11a1bb4b597a871b1/main.c#L34
https://github.com/StefForBSI/JeudeLOieGrA/blob/9603d14fd09dd2746ffd86e11a1bb4b597a871b1/main.c#L43

**Comment by 0xN0x** [comment]
Effectivement la doc originelle du projet était éronnée sur cette fonction, je corrige le main.

**Comment by 0xN0x** [comment]
#15 Fixed
